name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: docker/cache-action@v2
        with:
          path: |
            ~/docker
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Build Docker image
        run: docker build -t your-repo/react-app:latest -f path/to/Dockerfile .
        # Update `path/to/Dockerfile` to the correct location of your Dockerfile

      - name: Push Docker image
        run: docker push your-repo/react-app:latest
        # Replace `your-repo/react-app:latest` with your actual repository and tag
